version: '3.8'

services:
  api:
    image: ledharaujo/ms-users:latest
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.users.rule=Host(`api.la.dev.br`) && PathPrefix(`/users`)"
        - "traefik.http.routers.users.entrypoints=websecure"
        - "traefik.http.routers.users.tls.certresolver=letsencrypt"
        - "traefik.http.routers.users.middlewares=users-strip-prefix"
        - "traefik.http.middlewares.users-strip-prefix.stripPrefix.prefixes=/users"
        - "traefik.http.services.users.loadbalancer.server.port=3334"

networks:
  traefik-public:
    external: true

